#!/bin/bash
echo `git describe --tags --abbrev=0 2> /dev/null`-`git log --oneline | wc -l`" ("`git rev-parse --abbrev-ref HEAD`"@"`git log --pretty=format:'%h' -n 1``[[ -z $(git status -s) ]] || echo '+'`")" > version.txt
git add version.txt
